// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: func.proto
// Original file comments:
// Protocol buffer for Func FaaS
//
#ifndef GRPC_func_2eproto__INCLUDED
#define GRPC_func_2eproto__INCLUDED

#include "func.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace func {

class FuncService final {
 public:
  static constexpr char const* service_full_name() {
    return "func.FuncService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status hook(::grpc::ClientContext* context, const ::func::HookRequest& request, ::func::HookReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::func::HookReply>> Asynchook(::grpc::ClientContext* context, const ::func::HookRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::func::HookReply>>(AsynchookRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::func::HookReply>> PrepareAsynchook(::grpc::ClientContext* context, const ::func::HookRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::func::HookReply>>(PrepareAsynchookRaw(context, request, cq));
    }
    virtual ::grpc::Status unhook(::grpc::ClientContext* context, const ::func::UnhookRequest& request, ::func::UnhookReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::func::UnhookReply>> Asyncunhook(::grpc::ClientContext* context, const ::func::UnhookRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::func::UnhookReply>>(AsyncunhookRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::func::UnhookReply>> PrepareAsyncunhook(::grpc::ClientContext* context, const ::func::UnhookRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::func::UnhookReply>>(PrepareAsyncunhookRaw(context, request, cq));
    }
    virtual ::grpc::Status event(::grpc::ClientContext* context, const ::func::EventRequest& request, ::func::EventReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::func::EventReply>> Asyncevent(::grpc::ClientContext* context, const ::func::EventRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::func::EventReply>>(AsynceventRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::func::EventReply>> PrepareAsyncevent(::grpc::ClientContext* context, const ::func::EventRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::func::EventReply>>(PrepareAsynceventRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void hook(::grpc::ClientContext* context, const ::func::HookRequest* request, ::func::HookReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void hook(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::func::HookReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void unhook(::grpc::ClientContext* context, const ::func::UnhookRequest* request, ::func::UnhookReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void unhook(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::func::UnhookReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void event(::grpc::ClientContext* context, const ::func::EventRequest* request, ::func::EventReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void event(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::func::EventReply* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::func::HookReply>* AsynchookRaw(::grpc::ClientContext* context, const ::func::HookRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::func::HookReply>* PrepareAsynchookRaw(::grpc::ClientContext* context, const ::func::HookRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::func::UnhookReply>* AsyncunhookRaw(::grpc::ClientContext* context, const ::func::UnhookRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::func::UnhookReply>* PrepareAsyncunhookRaw(::grpc::ClientContext* context, const ::func::UnhookRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::func::EventReply>* AsynceventRaw(::grpc::ClientContext* context, const ::func::EventRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::func::EventReply>* PrepareAsynceventRaw(::grpc::ClientContext* context, const ::func::EventRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status hook(::grpc::ClientContext* context, const ::func::HookRequest& request, ::func::HookReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::func::HookReply>> Asynchook(::grpc::ClientContext* context, const ::func::HookRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::func::HookReply>>(AsynchookRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::func::HookReply>> PrepareAsynchook(::grpc::ClientContext* context, const ::func::HookRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::func::HookReply>>(PrepareAsynchookRaw(context, request, cq));
    }
    ::grpc::Status unhook(::grpc::ClientContext* context, const ::func::UnhookRequest& request, ::func::UnhookReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::func::UnhookReply>> Asyncunhook(::grpc::ClientContext* context, const ::func::UnhookRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::func::UnhookReply>>(AsyncunhookRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::func::UnhookReply>> PrepareAsyncunhook(::grpc::ClientContext* context, const ::func::UnhookRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::func::UnhookReply>>(PrepareAsyncunhookRaw(context, request, cq));
    }
    ::grpc::Status event(::grpc::ClientContext* context, const ::func::EventRequest& request, ::func::EventReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::func::EventReply>> Asyncevent(::grpc::ClientContext* context, const ::func::EventRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::func::EventReply>>(AsynceventRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::func::EventReply>> PrepareAsyncevent(::grpc::ClientContext* context, const ::func::EventRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::func::EventReply>>(PrepareAsynceventRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void hook(::grpc::ClientContext* context, const ::func::HookRequest* request, ::func::HookReply* response, std::function<void(::grpc::Status)>) override;
      void hook(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::func::HookReply* response, std::function<void(::grpc::Status)>) override;
      void unhook(::grpc::ClientContext* context, const ::func::UnhookRequest* request, ::func::UnhookReply* response, std::function<void(::grpc::Status)>) override;
      void unhook(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::func::UnhookReply* response, std::function<void(::grpc::Status)>) override;
      void event(::grpc::ClientContext* context, const ::func::EventRequest* request, ::func::EventReply* response, std::function<void(::grpc::Status)>) override;
      void event(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::func::EventReply* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::func::HookReply>* AsynchookRaw(::grpc::ClientContext* context, const ::func::HookRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::func::HookReply>* PrepareAsynchookRaw(::grpc::ClientContext* context, const ::func::HookRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::func::UnhookReply>* AsyncunhookRaw(::grpc::ClientContext* context, const ::func::UnhookRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::func::UnhookReply>* PrepareAsyncunhookRaw(::grpc::ClientContext* context, const ::func::UnhookRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::func::EventReply>* AsynceventRaw(::grpc::ClientContext* context, const ::func::EventRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::func::EventReply>* PrepareAsynceventRaw(::grpc::ClientContext* context, const ::func::EventRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_hook_;
    const ::grpc::internal::RpcMethod rpcmethod_unhook_;
    const ::grpc::internal::RpcMethod rpcmethod_event_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status hook(::grpc::ServerContext* context, const ::func::HookRequest* request, ::func::HookReply* response);
    virtual ::grpc::Status unhook(::grpc::ServerContext* context, const ::func::UnhookRequest* request, ::func::UnhookReply* response);
    virtual ::grpc::Status event(::grpc::ServerContext* context, const ::func::EventRequest* request, ::func::EventReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_hook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_hook() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_hook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hook(::grpc::ServerContext* context, const ::func::HookRequest* request, ::func::HookReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requesthook(::grpc::ServerContext* context, ::func::HookRequest* request, ::grpc::ServerAsyncResponseWriter< ::func::HookReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_unhook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_unhook() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_unhook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status unhook(::grpc::ServerContext* context, const ::func::UnhookRequest* request, ::func::UnhookReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestunhook(::grpc::ServerContext* context, ::func::UnhookRequest* request, ::grpc::ServerAsyncResponseWriter< ::func::UnhookReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_event : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_event() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_event() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status event(::grpc::ServerContext* context, const ::func::EventRequest* request, ::func::EventReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestevent(::grpc::ServerContext* context, ::func::EventRequest* request, ::grpc::ServerAsyncResponseWriter< ::func::EventReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_hook<WithAsyncMethod_unhook<WithAsyncMethod_event<Service > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_hook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_hook() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::func::HookRequest, ::func::HookReply>(
          [this](::grpc::ServerContext* context,
                 const ::func::HookRequest* request,
                 ::func::HookReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->hook(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_hook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hook(::grpc::ServerContext* context, const ::func::HookRequest* request, ::func::HookReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void hook(::grpc::ServerContext* context, const ::func::HookRequest* request, ::func::HookReply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_unhook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_unhook() {
      ::grpc::Service::experimental().MarkMethodCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::func::UnhookRequest, ::func::UnhookReply>(
          [this](::grpc::ServerContext* context,
                 const ::func::UnhookRequest* request,
                 ::func::UnhookReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->unhook(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_unhook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status unhook(::grpc::ServerContext* context, const ::func::UnhookRequest* request, ::func::UnhookReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void unhook(::grpc::ServerContext* context, const ::func::UnhookRequest* request, ::func::UnhookReply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_event : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_event() {
      ::grpc::Service::experimental().MarkMethodCallback(2,
        new ::grpc::internal::CallbackUnaryHandler< ::func::EventRequest, ::func::EventReply>(
          [this](::grpc::ServerContext* context,
                 const ::func::EventRequest* request,
                 ::func::EventReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->event(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_event() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status event(::grpc::ServerContext* context, const ::func::EventRequest* request, ::func::EventReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void event(::grpc::ServerContext* context, const ::func::EventRequest* request, ::func::EventReply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_hook<ExperimentalWithCallbackMethod_unhook<ExperimentalWithCallbackMethod_event<Service > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_hook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_hook() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_hook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hook(::grpc::ServerContext* context, const ::func::HookRequest* request, ::func::HookReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_unhook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_unhook() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_unhook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status unhook(::grpc::ServerContext* context, const ::func::UnhookRequest* request, ::func::UnhookReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_event : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_event() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_event() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status event(::grpc::ServerContext* context, const ::func::EventRequest* request, ::func::EventReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_hook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_hook() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_hook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hook(::grpc::ServerContext* context, const ::func::HookRequest* request, ::func::HookReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requesthook(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_unhook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_unhook() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_unhook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status unhook(::grpc::ServerContext* context, const ::func::UnhookRequest* request, ::func::UnhookReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestunhook(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_event : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_event() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_event() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status event(::grpc::ServerContext* context, const ::func::EventRequest* request, ::func::EventReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestevent(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_hook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_hook() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->hook(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_hook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hook(::grpc::ServerContext* context, const ::func::HookRequest* request, ::func::HookReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void hook(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_unhook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_unhook() {
      ::grpc::Service::experimental().MarkMethodRawCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->unhook(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_unhook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status unhook(::grpc::ServerContext* context, const ::func::UnhookRequest* request, ::func::UnhookReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void unhook(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_event : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_event() {
      ::grpc::Service::experimental().MarkMethodRawCallback(2,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->event(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_event() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status event(::grpc::ServerContext* context, const ::func::EventRequest* request, ::func::EventReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void event(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_hook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_hook() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::func::HookRequest, ::func::HookReply>(std::bind(&WithStreamedUnaryMethod_hook<BaseClass>::Streamedhook, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_hook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status hook(::grpc::ServerContext* context, const ::func::HookRequest* request, ::func::HookReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedhook(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::func::HookRequest,::func::HookReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_unhook : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_unhook() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::func::UnhookRequest, ::func::UnhookReply>(std::bind(&WithStreamedUnaryMethod_unhook<BaseClass>::Streamedunhook, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_unhook() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status unhook(::grpc::ServerContext* context, const ::func::UnhookRequest* request, ::func::UnhookReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedunhook(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::func::UnhookRequest,::func::UnhookReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_event : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_event() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler< ::func::EventRequest, ::func::EventReply>(std::bind(&WithStreamedUnaryMethod_event<BaseClass>::Streamedevent, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_event() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status event(::grpc::ServerContext* context, const ::func::EventRequest* request, ::func::EventReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedevent(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::func::EventRequest,::func::EventReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_hook<WithStreamedUnaryMethod_unhook<WithStreamedUnaryMethod_event<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_hook<WithStreamedUnaryMethod_unhook<WithStreamedUnaryMethod_event<Service > > > StreamedService;
};

}  // namespace func


#endif  // GRPC_func_2eproto__INCLUDED
